# Generated by Django 5.0.14 on 2026-09-25 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ارسال')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='classrooms.classroom', verbose_name='کلاس')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام گفتگو',
                'verbose_name_plural': 'پیام\u200cهای گفتگو',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['classroom', 'created_at'], name='chat_class_created_idx')],
            },
        ),
    ]
