# Generated by Django 5.0.14 on 2026-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف\u200cشده توسط مدیر'),
        ),
    ]
