# Generated by Django 5.0.14 on 2026-09-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_deleted'),
        ('classrooms', '0003_remove_classroommember_unique_classroom_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_identity',
            field=models.CharField(default='', max_length=48, verbose_name='شناسهٔ فرستنده'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='classrooms.classroommember', verbose_name='عضو فرستنده'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(default='', max_length=80, verbose_name='نام فرستنده'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
    ]
