# Generated by Django 5.0.14 on 2026-09-25 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کلاس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('room_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='کد کلاس')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز کلاس (هش\u200cشده)')),
                ('is_password_protected', models.BooleanField(default=False, verbose_name='محافظت با رمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='مالک کلاس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'مالک'), ('MODERATOR', 'مدیر جلسه'), ('PRESENTER', 'ارائه\u200cدهنده'), ('STUDENT', 'دانش\u200cآموز')], default='STUDENT', max_length=20, verbose_name='نقش')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='عضویت فعال')),
                ('can_use_microphone', models.BooleanField(default=True, verbose_name='اجازه استفاده از میکروفون')),
                ('can_use_camera', models.BooleanField(default=True, verbose_name='اجازه استفاده از دوربین')),
                ('can_share_screen', models.BooleanField(default=False, verbose_name='اجازه اشتراک صفحه')),
                ('can_use_whiteboard', models.BooleanField(default=False, verbose_name='اجازه استفاده از تخته سفید')),
                ('can_send_messages', models.BooleanField(default=True, verbose_name='اجازه ارسال پیام')),
                ('can_upload_files', models.BooleanField(default=False, verbose_name='اجازه بارگذاری فایل')),
                ('can_raise_hand', models.BooleanField(default=True, verbose_name='اجازه بالا بردن دست')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classrooms.classroom', verbose_name='کلاس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو کلاس',
                'verbose_name_plural': 'اعضای کلاس',
                'ordering': ('role', 'joined_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='classroommember',
            constraint=models.UniqueConstraint(fields=('classroom', 'user'), name='unique_classroom_member'),
        ),
    ]
