# Generated by Django 5.0.14 on 2026-09-25 11:37

import classrooms.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ورود')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
            ],
            options={
                'verbose_name': 'رکورد حضور',
                'verbose_name_plural': 'رکوردهای حضور',
                'ordering': ('joined_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان جلسه')),
                ('status', models.CharField(choices=[('SCHEDULED', 'زمان\u200cبندی\u200cشده'), ('LIVE', 'در حال برگزاری'), ('ENDED', 'پایان\u200cیافته')], default='SCHEDULED', max_length=20, verbose_name='وضعیت')),
                ('timezone_name', models.CharField(default='UTC', max_length=64, verbose_name='منطقهٔ زمانی')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع برنامه\u200cریزی\u200cشده')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان برنامه\u200cریزی\u200cشده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسه\u200cها',
                'ordering': ('-scheduled_start', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=classrooms.models.classroom_upload_path, verbose_name='فایل')),
                ('original_name', models.CharField(max_length=255, verbose_name='نام اصلی')),
                ('size', models.PositiveBigIntegerField(verbose_name='اندازه (بایت)')),
                ('content_type', models.CharField(max_length=128, verbose_name='نوع محتوا')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
            ],
            options={
                'verbose_name': 'فایل اشتراکی',
                'verbose_name_plural': 'فایل\u200cهای اشتراکی',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_file_upload',
            field=models.BooleanField(default=True, verbose_name='بارگذاری فایل (غیر مالک)'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_student_camera',
            field=models.BooleanField(default=True, verbose_name='دوربین دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_student_chat',
            field=models.BooleanField(default=True, verbose_name='گفتگوی دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_student_mic',
            field=models.BooleanField(default=True, verbose_name='میکروفون دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_student_screen_share',
            field=models.BooleanField(default=False, verbose_name='اشتراک صفحه دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_student_whiteboard',
            field=models.BooleanField(default=False, verbose_name='تختهٔ دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='chat_disabled',
            field=models.BooleanField(default=False, verbose_name='قطع کامل گفتگو'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='current_page',
            field=models.PositiveIntegerField(default=1, verbose_name='صفحهٔ جاری'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='enable_waiting_room',
            field=models.BooleanField(default=False, verbose_name='اتاق انتظار'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='کلاس قفل است'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ممنوعیت تا'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='camera_disabled',
            field=models.BooleanField(default=False, verbose_name='دوربین غیرفعال توسط مدیر'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='can_present',
            field=models.BooleanField(default=False, verbose_name='اجازه ارائه'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='hand_raised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بالا بردن دست'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='in_waiting_room',
            field=models.BooleanField(default=False, verbose_name='در اتاق انتظار'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='بی\u200cصدا توسط مدیر'),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='can_use_camera',
            field=models.BooleanField(default=True, verbose_name='اجازه دوربین'),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='can_use_microphone',
            field=models.BooleanField(default=True, verbose_name='اجازه میکروفون'),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='can_use_whiteboard',
            field=models.BooleanField(default=False, verbose_name='اجازه تخته سفید'),
        ),
        migrations.AddIndex(
            model_name='classroommember',
            index=models.Index(fields=['classroom', 'is_active'], name='mbr_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='classroommember',
            index=models.Index(fields=['classroom', 'role'], name='mbr_class_role_idx'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classrooms.classroommember', verbose_name='عضو'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classrooms.classroom', verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='میزبان'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classrooms.classroomsession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classrooms.classroom', verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='classrooms.classroomsession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='بارگذار'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='current_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classrooms.sharedfile', verbose_name='فایل در حال ارائه'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['owner', 'created_at'], name='cls_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsession',
            index=models.Index(fields=['classroom', 'status'], name='sess_class_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'user'], name='att_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfile',
            index=models.Index(fields=['classroom', 'uploaded_at'], name='file_class_uploaded_idx'),
        ),
    ]
