# Generated by Django 5.0.14 on 2026-09-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_attendancerecord_classroomsession_sharedfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroommember',
            name='unique_classroom_member',
        ),
        migrations.AddField(
            model_name='classroom',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='رنگ اصلی کلاس'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='allow_guests',
            field=models.BooleanField(default=True, verbose_name='ورود مهمان با لینک'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='classroom_logos/', verbose_name='لوگوی کلاس'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='show_chat_default',
            field=models.BooleanField(default=True, verbose_name='نمایش گفتگو به\u200cصورت پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='welcome_message',
            field=models.TextField(blank=True, verbose_name='پیام خوش\u200cآمدگویی'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='guest_uid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='شناسهٔ مهمان'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='مهمان'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالک'), ('MODERATOR', 'مدیر جلسه'), ('PRESENTER', 'ارائه\u200cدهنده'), ('STUDENT', 'دانش\u200cآموز'), ('GUEST', 'مهمان')], default='STUDENT', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddConstraint(
            model_name='classroommember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('classroom', 'user'), name='unique_classroom_member'),
        ),
    ]
