# Generated by Django 5.0.14 on 2026-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_remove_classroommember_unique_classroom_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='whiteboard_open',
            field=models.BooleanField(default=False, verbose_name='تختهٔ سفید باز است'),
        ),
    ]
