# Generated by Django 5.0.14 on 2026-09-26 14:54

import classrooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_backfill_can_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='pdf_version',
            field=models.FileField(blank=True, null=True, upload_to=classrooms.models.classroom_upload_path, verbose_name='نسخهٔ PDF'),
        ),
    ]
