# Generated by Django 5.0.14 on 2026-09-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_sharedfile_pdf_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommember',
            name='guest_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP مهمان هنگام ورود'),
        ),
    ]
