# Generated by Django 5.0.14 on 2026-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='density',
            field=models.CharField(choices=[('comfortable', 'راحت'), ('compact', 'فشرده')], default='comfortable', max_length=12, verbose_name='تراکم رابط'),
        ),
        migrations.AddField(
            model_name='user',
            name='landing_page',
            field=models.CharField(choices=[('dashboard', 'داشبورد'), ('home', 'صفحهٔ خانه')], default='dashboard', max_length=20, verbose_name='صفحهٔ فرود'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduce_animations',
            field=models.BooleanField(default=False, verbose_name='کاهش انیمیشن\u200cها'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'خودکار (سیستم)'), ('light', 'روشن'), ('dark', 'تیره')], default='system', max_length=10, verbose_name='پوسته'),
        ),
    ]
