# Generated by Django 5.0.14 on 2026-09-26 15:32

import assignments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0007_classroommember_guest_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='شرح تکلیف')),
                ('due_at', models.DateTimeField(verbose_name='مهلت ارسال')),
                ('max_score', models.PositiveIntegerField(default=20, verbose_name='بارم کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classrooms.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
                'ordering': ('-due_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='متن پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to=assignments.models.assignment_upload_path, verbose_name='فایل پاسخ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, verbose_name='بازخورد')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='تکلیف')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='classrooms.classroommember', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'ارسال پاسخ',
                'verbose_name_plural': 'ارسال\u200cهای پاسخ',
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'member'), name='unique_submission'),
        ),
    ]
