# Generated by Django 5.0.14 on 2026-09-26 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0007_classroommember_guest_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classrooms.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پرسش')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='بارم')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش\u200cها',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن گزینه')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینهٔ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.quizquestion', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='quizzes.quiz', verbose_name='آزمون')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_quiz_runs', to='classrooms.classroommember', verbose_name='شروع\u200cکننده')),
            ],
            options={
                'verbose_name': 'اجرای آزمون',
                'verbose_name_plural': 'اجراهای آزمون',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='زمان پاسخ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='classrooms.classroommember', verbose_name='عضو')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizoption', verbose_name='گزینهٔ انتخابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizquestion', verbose_name='پرسش')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizrun', verbose_name='اجرا')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('run', 'member', 'question'), name='unique_quiz_answer'),
        ),
    ]
