# Generated by Django 5.0.14 on 2026-09-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_attendancerecord_classroomsession_sharedfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='classrooms.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'تخته سفید',
                'verbose_name_plural': 'تخته\u200cهای سفید',
            },
        ),
        migrations.CreateModel(
            name='WhiteboardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.JSONField(verbose_name='عملیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='whiteboard.whiteboard', verbose_name='تخته')),
            ],
            options={
                'verbose_name': 'رویداد تخته',
                'verbose_name_plural': 'رویدادهای تخته',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['whiteboard', 'id'], name='wb_board_id_idx')],
            },
        ),
    ]
