# Generated by Django 5.0.14 on 2026-09-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboardevent',
            name='actor_identity',
            field=models.CharField(default='', max_length=48, verbose_name='شناسهٔ کاربر'),
        ),
        migrations.AlterField(
            model_name='whiteboardevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
