# Generated by Django 5.0.14 on 2026-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_whiteboardevent_actor_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboardevent',
            name='page',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='صفحه'),
        ),
    ]
